server:
  port: 8091

spring:
  application:
    name: sys-regsiter
app:
  id: sys-regsiter #apollo配置中心应用名
apollo:
  meta: http://localhost:8080 #apollo地址
  bootstrap:
    enabled: true #是否启用apollo, 不使用apollo 请剔除该包
    namespaces: application.yml
