server:
  port: 8083

spring:
  application:
    name: sys-gateway
app:
  id: sys-gateway #apollo配置中心应用名
apollo:
  meta: http://localhost:8080 #apollo地址
  bootstrap:
    enabled: true #是否启用apollo, 不使用apollo 请剔除该包
    namespaces: application.yml

