server:
  port: 8083

spring:
  application:
    name: sys-gateway

app:
  id: sys-gateway #apollo配置中心应用名
apollo:
  meta: http://localhost:8080 #apollo地址
  bootstrap:
    enabled: true #是否启用apollo, 不使用apollo 请剔除该包
    namespaces: application.yml
#    eagerLoad:
#      enabled: true #是apollo中配置的日志几级别生效

logging:
  level:
    com.zl: debug

security:
  username: app
  password: 123456
  whitelist:
    - /sys-uua/oauth/token
    - /sys-uua/oauth/authorize
    - /sys-uua/login
    - /sys-admin-service/dict/dictTree
    - /sys-admin-service/user/register

swagger:
  enabled: false
