server:
  port: 8094

spring:
  application:
    name: sys-admin-service

app:
  id: sys-admin #apollo配置中心应用名
apollo:
  meta: http://192.168.59.1:8080 #apollo地址
  bootstrap:
    enabled: true #是否启用apollo, 不使用apollo 请剔除该包
    namespaces: application.yml

#logging:
#  level:
#    root: debug
#    com.zl: debug

#swagger:
#  enable: true
#  oauth:
#    url: http://localhost:8083/oauth_token
#    clien_id: app

