server:
  port: 80
#  servlet:
  #    context-path: /sys-admin-service
spring:
  application:
    name: sys-admin-service
  datasource:
    username: zhongliang
    password: 123456
    url: jdbc:mysql://localhost:3306/sysmanage?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  #配置项目热部署
  devtools:
    restart:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml

logging:
  level:
    com.zl.sysadminservice: debug



md5:
  key: 12345678
